In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 128], dtype=np.uint64)
print(a)

[  1   2   3   4   5 128]


In [5]:
np.arange(10, 15, 1)

array([10, 11, 12, 13, 14])

In [7]:
a = [
    [1, 2],
    [3, 4]
] 
b = a[:1]
b[0][0] = 10
b

[[10, 2]]

In [8]:
a

[[10, 2], [3, 4]]

In [9]:
s = [1, 2, 2, 3, 4, 5]
c = s[:3]
c[0] = 5
c

[5, 2, 2]

In [10]:
s

[1, 2, 2, 3, 4, 5]

In [3]:
j = np.random.randint(1, 20, size=(4, 4))
j

array([[19,  6,  8, 18],
       [17,  9, 16,  3],
       [10,  4, 12,  1],
       [17,  7,  5,  1]], dtype=int32)